# Generated by Django 5.0.6 on 2024-07-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_new_user_views_alter_new_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='view',
            new_name='views',
        ),
    ]
