# Generated by Django 5.0.6 on 2024-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_new_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее кол-во просмотров'),
        ),
    ]
