# Generated by Django 5.0.6 on 2024-07-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_new_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее кол-во просмотров'),
        ),
    ]
