# Generated by Django 5.0.6 on 2024-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_costumer_views'),
        ('costumerapp', '0004_alter_profile_bio_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costumer_views',
            field=models.ManyToManyField(default=0, to='costumerapp.costumer', verbose_name='Просмотры пользователей'),
        ),
    ]
