# Generated by Django 5.0.7 on 2024-07-25 07:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Контактный номер телефона', max_length=35, null=True, region='KG', verbose_name='Номер телефона'),
        ),
    ]
