# Generated by Django 5.0.6 on 2024-07-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerapp', '0003_profile_alter_costumer_age_alter_costumer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='соц.сети'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='costumerapp.costumer', verbose_name='Имя'),
        ),
    ]
