# Generated by Django 5.0.6 on 2024-07-12 04:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumerapp', '0005_alter_profile_phone_number_alter_profile_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Контактный номер телефона', max_length=35, null=True, region='KG', verbose_name='Номер телефона'),
        ),
    ]
